services:
  os:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Argmax123!"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - argmax
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  web:
    build:
      context: web
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - OPENSEARCH_URL=http://os:9200
    ports:
      - "8080:8080"
    volumes:
      - ./web/src:/app/web
    networks:
      - argmax
    depends_on:
      os:
        condition: service_healthy

  nb:
    build:
      context: nb
      dockerfile: Dockerfile
    environment:
      - OPENSEARCH_URL=http://os:9200
    ports:
      - "8888:8888"
    volumes:
      - ./nb/src:/usr/src/app
    networks:
      - argmax
    depends_on:
      os:
        condition: service_healthy

volumes:
  opensearch-data:

networks:
  argmax:
    driver: bridge
